import { execFile } from "child_process";
import * as path from "path";
import { ParamDef } from "./paramSet";

/** Whether a `dakota` binary is on `PATH` — gates whether the Dakota
 *  export action is offered at all (it's an optional power-user backend,
 *  never a requirement; see the module doc below). */
export function detectDakota(): Promise<boolean> {
  return new Promise(resolve => {
    execFile("dakota", ["-version"], { timeout: 5000 }, err => resolve(!err));
  });
}

/**
 * Dakota (Sandia) is a real, actively-maintained standalone application
 * for optimization/UQ/DOE/sensitivity analysis — but it's a separately
 * installed native app (not a library), so it's an *optional* export
 * target, never a requirement: this only generates a starting
 * `dakota.in` from the same parameter definitions the native sweep
 * (`sweepRunner.ts`) uses, for a user who already has Dakota and wants
 * its actual DOE/optimization/UQ algorithms instead of a plain grid.
 *
 * Dakota's own "black-box" pattern: it writes a parameters file each
 * iteration and calls an external analysis driver, which is expected to
 * substitute the parameters into the simulation's input (traditionally
 * via Dakota's `dprepro`/`pyprepro` templating), run it, and write back
 * a results file in Dakota's expected format. `analysisDriverScript`
 * below generates that driver, wired to the same `{file, blockPath,
 * key}` targets — reusing `substitute.ts` via a tiny Node shim so the
 * driver doesn't need Dakota's own templating tool at all.
 */

function dakotaVarName(p: ParamDef): string {
  // Dakota variable names must be valid identifiers.
  return p.name.replace(/[^A-Za-z0-9_]/g, "_");
}

/** A `dakota.in` multidim parameter study over the given parameters —
 *  the direct analogue of `cartesianVariants()`'s grid, expressed in
 *  Dakota's own input format. Numeric parameters become
 *  `discrete_state_set` values; everything is treated as a string set
 *  since sweep values here are arbitrary dictionary text, not
 *  necessarily numbers. */
export function buildDakotaInput(params: ParamDef[], analysisDriver: string): string {
  const names = params.map(dakotaVarName);
  const lines: string[] = [
    "# Generated by the OpenFOAM VS Code extension's parametric-study export.",
    "# Runs the same sweep as \"OpenFOAM: Start Parametric Study\", via Dakota's",
    "# own study/optimization/UQ methods instead of a plain grid.",
    "",
    "environment",
    "    tabular_data",
    "        tabular_data_file 'dakota_results.dat'",
    "",
    "method",
    "    multidim_parameter_study",
    `    partitions = ${params.map(p => p.values.length - 1).join(" ")}`,
    "",
    "variables",
    `    discrete_state_set string = ${params.length}`,
    `        num_set_values = ${params.map(p => p.values.length).join(" ")}`,
    ...params.map(p => `        set_values ${p.values.map(v => `'${v}'`).join(" ")}`),
    `        descriptors ${names.map(n => `'${n}'`).join(" ")}`,
    "",
    "interface",
    "    fork",
    `        analysis_drivers = '${analysisDriver}'`,
    "        parameters_file = 'params.in'",
    "        results_file = 'results.out'",
    "",
    "responses",
    "    response_functions = 1",
    "    descriptors = 'objective'",
    "    no_gradients",
    "    no_hessians",
    "",
  ];
  return lines.join("\n");
}

/**
 * A Node analysis-driver script Dakota `fork`s each iteration: reads the
 * Dakota-format parameters file it's given, maps them back onto
 * `{file, blockPath, key}` targets via the same `substitute.ts` used by
 * the native sweep, runs the solver command the user fills in, and
 * writes Dakota's expected results file.
 */
export function buildAnalysisDriverScript(caseRoot: string, params: ParamDef[], extensionPath: string): string {
  const targets = params.map(p => ({ varName: dakotaVarName(p), file: p.file, blockPath: p.blockPath, key: p.key }));
  return `#!/usr/bin/env node
// Dakota analysis driver — generated by the OpenFOAM VS Code extension.
// Dakota calls this as:  driver.js params.in results.out
"use strict";
const fs = require("fs");
const path = require("path");

const CASE_ROOT = ${JSON.stringify(caseRoot)};
const TARGETS = ${JSON.stringify(targets, null, 2)};

// TODO: point this at your solver invocation (e.g. "simpleFoam -case " + CASE_ROOT).
const SOLVER_COMMAND = ${JSON.stringify("echo 'TODO: run the solver, then set objective in results.out'")};

function parseDakotaParams(text) {
  // Dakota's "standard" params format: "<value> <descriptor>" per line.
  const values = {};
  for (const line of text.split("\\n")) {
    const m = line.trim().match(/^'?([^'\\s]+)'?\\s+(\\S+)$/);
    if (m) values[m[2]] = m[1];
  }
  return values;
}

const [, , paramsFile, resultsFile] = process.argv;
const values = parseDakotaParams(fs.readFileSync(paramsFile, "utf8"));

// Substitute each parameter's Dakota-chosen value into its target file,
// reusing the extension's own tree-sitter-based substitution. Absolute
// paths into the installed extension — if you move this driver script
// to another machine, point these at that machine's copy instead.
const { getParser, parseText } = require(${JSON.stringify(path.join(extensionPath, "out", "treeSitter", "parser"))});
const { substituteEntryValue, replaceRange } = require(${JSON.stringify(path.join(extensionPath, "out", "parametric", "substitute"))});

(async () => {
  const parser = await getParser();
  for (const t of TARGETS) {
    const filePath = path.join(CASE_ROOT, t.file);
    let text = fs.readFileSync(filePath, "utf8");
    const tree = parseText(parser, text);
    const sub = substituteEntryValue(tree, t.blockPath, t.key, values[t.varName]);
    if (sub) fs.writeFileSync(filePath, replaceRange(text, sub.range, sub.text), "utf8");
  }

  const { execSync } = require("child_process");
  execSync(SOLVER_COMMAND, { cwd: CASE_ROOT, stdio: "inherit" });

  // TODO: replace 0.0 with the actual scalar objective extracted from the run.
  fs.writeFileSync(resultsFile, "0.0 objective\\n");
})();
`;
}
